project:
  type: website
  output-dir: docs
  
website:
  title: "Data Science Collaborative"
  navbar:
    left:
    - text: About
      href: index.qmd
      icon: fa-home
    - text: Projects
      href: setup.qmd
    - text: Team
      href: hosting.qmd
    - text: Powered by OTTR
      href: https://www.ottrproject.org/

