project:
  type: website
  output-dir: docs
  
website:
  title: "Data Science Collaborative"
  navbar:
    left:
    - text: Home
      href: index.qmd
      icon: fa-home
    - text: Projects
      href: projects.qmd
    - text: Team
      href: hosting.qmd
  page-footer:
    center: 
      - text: Powered by OTTR
        href: https://www.ottrproject.org/

