project:
  type: website
  output-dir: docs
  
website:
  title: "OTTR Template Website"
  navbar:
    left:
    - text: ""
      href: index.qmd
      icon: fa-home
    - text: Fred Hutch DaSL
      href: setup.qmd
    - text: UT Austin
      href: hosting.qmd
    - text: Editing
      href: editing.qmd
    - text: JHU
      href: style.qmd
    - text: 4. Git Actions
      href: git_actions.qmd
    - text: More ottr docs
      href: https://www.ottrproject.org/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
