project:
  type: website
  output-dir: docs
  
website:
  title: "Data Science Collaborative"
  navbar:
    left:
    - text: Home
      href: index.qmd
    - text: Projects
      href: projects.qmd
    - text: Software
      href: software.qmd
    - text: Team
      href: team.qmd
    - text: Join
      href: join.qmd
  page-footer:
    center: 
      - text: Powered by OTTR
        href: https://www.ottrproject.org/

