project:
  type: website
  output-dir: docs
  
website:
  navbar:
    left:
    - text: Data Science Collaborative
      href: index.qmd
      icon: fa-home
    - text: Projects
      href: setup.qmd
    - text: Team
      href: hosting.qmd
  page-footer:
    center: 
      - text: Powered by OTTR
        href: https://www.ottrproject.org/