project:
  type: website
  output-dir: docs
  
website:
  title: "Data Science Collaborative"
  navbar:
    left:
    - text: Home
      href: index.qmd
    - text: Projects
      menu:
        - text: AnVIL
          href: projects.qmd#anvil
        - text: Community Data Science
          href: projects.qmd#baltimore-community-data-science
    - text: Software
      href: software.qmd
    - text: Team
      menu:
        - text: Fred Hutch
          href: team.qmd#fred-hutch
        - text: JHU
          href: team.qmd#johns-hopkins-university
    - text: Join
      href: join.qmd
  page-footer:
    center: 
      - text: Powered by OTTR
        href: https://www.ottrproject.org/

